version: '3.8'

services:
    db:
        image: postgres:12.2-alpine
        container_name: 'go-api-db'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=go_api
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        networks:
            - fullstack
        volumes:
            - datebase_postgres:/var/lib/postgresql/data
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: ./.env
        container_name: 'go-api'
        ports:
            - '4000:4000'
        depends_on:
            - db
        networks:
            - fullstack
volumes:
    datebase_postgres:
networks:
    fullstack:
        driver: bridge
